apiVersion: v1
kind: Service
metadata:
  name: svc-basic-app
  namespace: default  # Avoid errors with ansible
spec:
  type: NodePort
  selector:
    app: deployment-basic-app
  ports:
  - port: 3000
    nodePort: 30001
