name: Create Infrastructure with AWS

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: terraform/infra

    steps:
      # We need this to work with our folders
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var "node_role_arn=${NODE_ROLE_ARN}" \
          -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
          -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
          -var "aws_session_token=${AWS_SESSION_TOKEN}" \
          -var "aws_region=${AWS_REGION}"

      - name: Terraform Apply
        run: terraform plan -var "node_role_arn=${NODE_ROLE_ARN}" \
          -var "aws_access_key=${AWS_ACCESS_KEY_ID}" \
          -var "aws_secret_key=${AWS_SECRET_ACCESS_KEY}" \
          -var "aws_session_token=${AWS_SESSION_TOKEN}" \
          -var "aws_region=${AWS_REGION}" \
          -auto-approve

      - name: Terraform Output
        id: output
        run: terraform output -json

      - name: Display Application DNS
        run: |
          echo "Application URL: ${{ steps.output.outputs.APP_URL }}"

      - name: Display Application IP
        run: |
          echo "Application IP: ${{ steps.output.outputs.APP_IP }}"
