name: AWS - Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    defaults:
      run:
        working-directory: terraform/infra

    steps:
      # We need this to work with our folders
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve \
          -var="node_role_arn=${{ secrets.NODE_ROLE_ARN }}" \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var="aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="aws_bucket_name=${{ secrets.AWS_BUCKET_NAME }}"